spring:
  application:
    name: InMemory-Caching

  datasource:
    url: jdbc:mysql://localhost:3306/inmemory-caching?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        cache:
          use_second_level_cache: true
          region:
            '[factory_class]': org.hibernate.cache.jcache.JCacheRegionFactory
          use_query_cache: true
